apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld
spec:
  replicas: 15
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        name: helloworld