apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-secret
  name: helloworld-secret
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld-secret
    resources: {}
    volumeMounts:
    - name: my-secret-volume
      mountPath: /my-secret
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: my-secret-volume
      secret:
        secretName: my-secret
status: {}
