apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-config
  name: helloworld-config
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld-config
    resources: {}
    volumeMounts:
    - name: my-config-volume
      mountPath: /my-config/TEST_ENV
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: my-config-volume
      configMap:
        name: my-config
        items:
          - key: TEST_ENV
            path: keys
status: {}
